#!python
from setuptools import setup, find_packages

setup(name='lovely.rating',
      version='0.2',
      author = "Lovelysystems",
      author_email = "office@lovelysystems.com",
      description = "A rating engine for zope 3",
      license = "ZPL 2.1",
      keywords = "zope3 web20 rating",
      url='svn://svn.zope.org/repos/main/lovely.rating',
      packages=find_packages('src'),
      include_package_data=True,
      package_dir = {'':'src'},
      extras_require=dict(test=['zope.app.testing',
                                'zope.testing',
                                ]),
      namespace_packages=['lovely'],
      install_requires = ['setuptools',
                          'ZODB3',
                          'pytz',
                          'zope.app.container',
                          'zope.app.generations',
                          'zope.app.zopeappgenerations',
                          'zope.component',
                          'zope.i18nmessageid',
                          'zope.interface',
                          'zope.schema',
                          ],
     )
